sudo: false
language: python
python:
  - "3.5"
  - "3.6"

env:
  matrix:
    - DB=postgres

matrix:
  include:
    - python: 3.5
      env: DB=sqlite

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 7
  - node -v
  - if [[ "$DB" == "postgres" ]]; then psql -c 'create database nextcloudappstore;' -U postgres; fi

install:
  - make dev-setup db="$DB" pyvenv="pyvenv"
  - npm -g install yarn
  - yarn install tslint

script:
  - ./node_modules/.bin/tslint "./nextcloudappstore/core/static/assets/**/*.ts"
  - make test

services:
  - postgresql

addons:
  firefox: "latest"
