dist: trusty
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  #- "3.7"

env:
  matrix:
    - DB=postgres

matrix:
  include:
    - python: 3.5
      env: DB=sqlite

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 8
  - if [[ "$DB" == "postgres" ]]; then psql -c 'create database nextcloudappstore;' -U postgres; fi
  # install geckodriver for frontend tests
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz -O geckodriver.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - npm -g install yarn
  - make dev-setup db="$DB" venv_bin=""
  - make l10n venv_bin=""
  - yarn add tslint

script:
  - ./node_modules/.bin/tslint "./nextcloudappstore/core/static/assets/**/*.ts"
  - make test venv_bin=""

after_success:
  - coveralls

services:
  - postgresql

addons:
  firefox: "latest"
  postgresql: "9.5"
