sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
    - DB=postgres

matrix:
  include:
    - python: 3.4
      env: DB=sqlite

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip
  - if [[ "$DB" == "postgres" ]]; then psql -c 'create database nextcloudappstore;' -U postgres; fi

install:
  - make dev-setup db="$DB" pyvenv="pyvenv"

script:
  - make test


services:
  - postgresql
